<?php
foreach (glob("/../Modules/*.php") as $filename){
    include $filename;
}
use Modules\DESIGN;
use Modules\DRIVERS;
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Dashboard</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?php  echo DESIGN::getBasicLibrary();  ?>
    <link href="/lib/css/calentim.min.css" rel="stylesheet"/>
    <script src="/lib/js/moment.min.js"></script>
    <script src="/lib/js/calentim.min.js"></script>
    <style>
      .ui.paddingless.segment{
        padding: 0 !important;
      }
      .configView{
        padding: 10px 0px 0px 0px !important;;
      }
    </style>
  </head>
  <body>
    <div class="pusher">
      <?php // echo DESIGN::renderMenuDesk(4);  ?>
      <div class="configView">


        <div class="ui raised segment">
          <div class="ui top attached grey label">
             <h4> <i class="clipboard icon"></i>Bitacora</h4>
          </div>
          <div class="lildivider"></div>
          <div class="groupsections" id="sectionListBin">
            <div class="">
              <!--
              <div class="flotaizq jalarriba">
                <div class="ui mini icon green button" onclick="runCreate()">
                  <i class="file icon"></i>
                </div>
              </div>
              -->
              <div class="flotader jalarriba">
                <div class="ui mini input ">
                  <input type="text" class="calendas" name="iniBinPer" id="iniBinPer" value="" placeholder="Fecha Inicio">
                </div>
                <div class="ui mini input ">
                  <input type="text" class="calendas" name="finBinPer" id="finBinPer" value="" placeholder="Fecha Fin">
                </div>
                <div class="ui mini icon blue button" onclick="listadoRes()">
                  <i class="search icon"></i>&ensp;Nueva
                </div>
              </div>
              <div class="">&ensp;</div>
            </div> <!-- Cabecera Seccion-->
            <div class="ui divider"></div>
            <table class="ui selectable celled table" id="listadoBitacoras"  style="width:100% !important">
              <thead>
                <tr align="center">
                  <td class="one wide subtitleBlack">Codigo</td>
                  <td class="three wide subtitleBlack">Nombre</td>
                  <td class="one wide subtitleBlack">Fecha Inicio</td>
                  <td class="one wide subtitleBlack">Fecha Fin</td>
                  <td class="one wide subtitleBlack">Estatus</td>
                  <td class="subtitleBlack">Comentarios</td>
                  <td class="three wide subtitleBlack">Propietario</td>
                  <td class="one wide subtitleBlack">&ensp;</td>
                </tr>
              </thead>
              <tbody id="datamaster2" style="font-size: .8rem;"></tbody>
            </table>
          </div>
          <div class="groupsections" id="sectionSelRes" style="display:none;">
            <div class="">
              <div class="flotaizq jalarriba">
                <div class="ui mini icon green button" onclick="runBuildBin()">
                  <i class="save icon"></i>&ensp;Guardar
                </div>
              </div>
              <div class="flotaizq jalarriba">
                <div class="ui mini icon button" onclick="changeViewBin('catalogo')">
                  <i class="columns icon"></i>&ensp;Catalogo
                </div>
              </div>
              <div class="flotader jalarriba">
                <div class="ui  icon search" >
                  <div class="ui right action mini input">
                    <input type="text" name="findt" id="findt" placeholder="Nombre o Referencia" autocomplete="off" >
                    <a class="ui blue mini button" title="Buscar" onclick="showList('target',$('#findt').val())">
                      &ensp;<i class="ui search icon"></i>
                    </a>
                  </div>
                </div>
              </div>
              <div class="">&ensp;</div>
            </div> <!-- Cabecera Seccion-->
            <div class="ui divider"></div>
            <table class="ui selectable celled table" id="example"  style="width:100% !important">
              <thead>
                <tr align="center">
                  <td class="subtitleBlack">&ensp;</td>
                  <td class="one wide subtitleBlack">Folio</td>
                  <td class="two wide subtitleBlack">Cliente</td>
                  <td class="one wide subtitleBlack">Email</td>
                  <td class="one wide subtitleBlack">Telefono</td>
                  <td class="one wide subtitleBlack">Servicio</td>
                  <td class="two wide subtitleBlack">Origen</td>
                  <td class="two wide subtitleBlack">Destino</td>
                  <td class="one wide subtitleBlack">VCODE</td>
                  <td class="one wide subtitleBlack">Seats</td>
                  <td class="two wide subtitleBlack">PickUp</td>
                  <td class="one wide subtitleBlack">Metodo</td>
                  <td class="one wide subtitleBlack">Total</td>
                  <td class="subtitleBlack">&ensp;</td>
                </tr>
              </thead>
              <tbody id="datamaster" style="font-size: .8rem;"></tbody>
            </table>

          </div> <!-- Seccion-->
          <div class="groupsections" id="sectionDetBin" style="display:none;">
            <div class="">
              <div class="flotaizq jalarriba">
                <div class="ui mini icon button" onclick="changeViewBin('catalogo')">
                  <i class="columns icon"></i>&ensp;Catalogo
                </div>
              </div>
              <div class="flotaizq jalarriba">
                <div class="ui mini icon button" onclick="printar()">
                  <i class="print icon"></i>&ensp;Imprimir
                </div>
              </div>
              <div class="">&ensp;</div>
            </div> <!-- Cabecera Seccion-->
            <div class="ui divider"></div>
            <div class="subtitleBlack">
              Codigo: <span id="identificadorDetBin"></span>
            </div>
            <div class="ui divider"></div>
            <table class="ui selectable celled table" id="idBitacoraDetalle"  style="width:100% !important">
              <thead>
                <tr align="center">
                  <td class="one wide subtitleBlack">&ensp;</td>
                  <td class="one wide subtitleBlack">Fecha</td>
                  <td class="three wide subtitleBlack">Cliente</td>
                  <td class="one wide subtitleBlack">PAX</td>
                  <td class="one wide subtitleBlack">Tipo</td>
                  <td class="two wide subtitleBlack">Services</td>
                  <td class="two wide subtitleBlack">Flight Info</td>
                  <td class="three wide subtitleBlack">From</td>
                  <td class="three wide subtitleBlack">Destination</td>
                  <td class="one wide subtitleBlack">Conductor</td>
                <!--  <td class="one wide subtitleBlack">Vehiculo</td> -->
                  <td class="one wide subtitleBlack">Comentarios</td>
                  <td class="one wide subtitleBlack">Coordinador</td>
                </tr>
              </thead>
              <tbody id="datamaster3" style="font-size: .8rem;"></tbody>
            </table>
          </div>
        </div> <!-- Segmento-->

      </div> <!-- View-->
    </div> <!-- Pusher-->

    <div class="ui viewReserva basic modal">
      <i class="icon close" style="display:none;" id="closmodview"></i>
      <div class="ui segment" id="frmnewoff">
        <div class="ui top attached blue label">
          <div class="flotaizq">
            RESERVA
          </div>
          <div class="flotader"><i class="icon close" onclick="$('#closmodview').trigger('click')"></i></div>
        </div>
        <div class="ui one column grid">
          <div class="column" style="border-right: solid 1px #e7e7e7;">

            <div class="">
              <table class="ui very basic striped fixed table">
                <tbody>
                  <tr>
                    <td class="" >
                      <div class="subtitleBlue">
                        <span class="lilcomment subtitleMoreGray">Folio:</span>&ensp; <span id="inIdRes"></span>
                      </div>
                    </td>
                    <td>
                      <div class="subtitleBlue" align="left">
                        <span class="lilcomment subtitleMoreGray">Estatus:</span>&ensp;<span id="inEstatusADD" class="subtitleBlack"></span><span id="inEstatusEXADD" class="lilcomment subtitleMoreGray"></span>
                      </div>
                    </td>
                    <td>
                      <div class="subtitleBlue" align="left">
                        <span class="lilcomment subtitleMoreGray">Metodo de Pago:</span>&ensp;<span id="inEstatusPAY" class="subtitleBlack"></span>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td >
                      <div class="subtitleBlue">
                        <span class="lilcomment subtitleMoreGray">Zona: </span>&ensp;<span id="inZona"></span>
                      </div>
                    </td>
                    <td class="">
                      <div class="subtitleBlue">
                        <span class="lilcomment subtitleMoreGray">Servicio:</span>&ensp; <span id="inServicio"></span>
                      </div>
                    </td>
                    <td >
                      <div class="subtitleBlue">
                        <span class="lilcomment subtitleMoreGray">Vehiculo: </span>&ensp;<span id="inVehicle"></span>
                      </div>
                    </td>
                  </tr>

                  <tr>
                    <td class="">
                      <div class="subtitleBlue">
                        <span class="lilcomment subtitleMoreGray">Adultos:</span>&ensp; <span id="inAdults"></span>
                      </div>
                    </td>
                    <td class="">
                      <div class="subtitleBlue">
                        <span class="lilcomment subtitleMoreGray">Niños:</span>&ensp; <span id="inKids"></span>
                      </div>
                    </td>
                    <td></td>
                  </tr>
                  <tr>
                    <td class="">
                      <div class="subtitleBlue">
                        <span class="lilcomment subtitleMoreGray">Parada:</span>&ensp; <span id="inStop"></span>
                      </div>
                    </td>
                    <td class="">
                      <div class="subtitleBlue">
                        <span class="lilcomment subtitleMoreGray">Child Seat:</span>&ensp; <span id="inChildSeat"></span>
                      </div>
                    </td>
                    <td class="">
                      <div class="subtitleBlue">
                        <span class="lilcomment subtitleMoreGray">Booster Seat:</span>&ensp; <span id="inBoosterSeat"></span>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="ui horizontal divider">
              <b>INFORMACION DE CONTACTO</b>
            </div>
            <table class="ui very basic striped fixed table">
              <tbody>
                <tr></tr>
                <tr>
                  <td class="">
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Nombre:</span>&ensp; <span id="inClie"></span>
                    </div>
                  </td>
                  <td class="">
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Email:</span>&ensp;<span id="inEmail"></span>
                    </div>
                  </td>
                  <td class="">
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Tel:</span>&ensp;<span id="inTel"></span>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>

            <div class="ui horizontal divider" align="left">
              <b>ARRIVAL</b>
            </div>
            <table class="ui very basic striped fixed table">
              <tbody>
                <tr></tr>
                <tr>
                  <td class="">
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Origen: </span><span id="inArrOrigen"></span>
                    </div>
                  </td>
                  <td class="">
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Destino: </span><span id="inArrDestino"></span>
                    </div>
                  </td>
                  <td >
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">PickUp: </span>&ensp;<span id="inDtArrPickup"></span>
                    </div>
                  </td>
                </tr>
                <tr>
                  <td>
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Aerolinea:</span>&ensp;<span id="inArrAirline"></span>
                    </div>
                  </td>
                  <td>
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Vuelo:</span>&ensp;<span id="inArrFlight"></span>
                    </div>
                  </td>
                  <td>
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Llegada:</span>&ensp;<span id="inDtArrAirPick"></span>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>

            <div class="ui horizontal divider" align="left">
              <b>DEPARTURE</b>
            </div>
            <table class="ui very basic striped fixed table">
              <tbody>
                <tr></tr>
                <tr>
                  <td class="">
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Origen: </span><span id="inDepOrigen"></span>
                    </div>
                  </td>
                  <td class="">
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Destino: </span><span id="inDepDestino"></span>
                    </div>
                  </td>
                  <td >
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">PickUp: </span>&ensp;<span id="inDtDepPickup"></span>
                    </div>
                  </td>
                </tr>
                <tr>
                  <td>
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Aerolinea:</span>&ensp;<span id="inDepAirline"></span>
                    </div>
                  </td>
                  <td>
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Vuelo:</span>&ensp;<span id="inDepFlight"></span>
                    </div>
                  </td>
                  <td>
                    <div class="subtitleBlue">
                      <span class="lilcomment subtitleMoreGray">Llegada:</span>&ensp;<span id="inDtDepAirPick"></span>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>

            <table class="ui very basic striped fixed table">
              <tbody>
                <tr></tr>
                <tr>
                  <td colspan="3">
                    <div class="subtitleBlue" align="center">
                      <span class="lilcomment subtitleMoreGray">Total:</span>&ensp;$<span id="inTotal" class="subtitleBlack"></span> USD
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

        </div>

      </div>
    </div>

    <div class="ui newBinnacleModal mini basic modal">
      <i class="icon close" style="display:none;margin-" id="closmod"></i>
      <div class="ui segment" id="">
        <div class="ui top attached blue label">
          <div class="flotaizq">
            Nueva Bitacora
          </div>
          <div class="flotader"><i class="icon close" onclick="$('#closmod').trigger('click')"></i></div>
        </div>
        <div class="toolildivider"></div>
        <div class="ui newBinnaclefrm form">
          <div class="field">
            <label for="">Nombre</label>
            <input type="text"  name="newBinName" id="newBinName" value="" placeholder="ej. Jueves">
          </div>
          <div class="field">
            <label for="">Estatus</label>
            <select name="newBinStat" id="newBinStat" class="ui dropdown mini input">
              <option value="proceso">Proceso</option>
              <option value="revision">Revision</option>
              <option value="concluida">Concluida</option>
            </select>
          </div>
          <div class="ui divider"></div>
          <div class="field" align="right">
            <div class="ui blue submit mini button" id="newbinsavebtn">
              <i class="save icon"></i>Guardar
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="ui asigndrivermod mini basic modal">
      <i class="icon close" style="display:none;" id="closmodchof"></i>
      <div class="ui segment" id="frmnewoff">
        <div class="ui top attached blue label">
          <div class="flotaizq">
            Asignar a <span id="asigndriverlbl"></span>
          </div>
          <div class="flotader"><i class="icon close" onclick="$('#closmodchof').trigger('click')"></i></div>
        </div>
        <div class="toolildivider"></div>
        <div class="ui asigndriverfrm form">
          <input type="hidden" name="idResAtAsign" id="idResAtAsign">
          <div class="field">
            <label for="">Conductor</label>
            <select name="idDrvToAsing" id="idDrvToAsing" class="ui dropdown mini input">
              <option value="">Seleccionar</option>
              <?php
                $temp["mode"]='selectlist';
                $driversList=DRIVERS::getList($temp);
                foreach ($driversList as $key => $value) {
                  echo '<option value="'.$value["codeDriver"].'">'.$value["name"].'</option>';
                }
              ?>
            </select>
          </div>
          <div class="ui divider"></div>
          <div class="field" align="right">
            <div class="ui blue submit mini button">
            <i class="check icon"></i>  Asignar
            </div>
          </div>
        </div>
      </div>
    </div>


    <?php echo DESIGN::getExtendedLibraryNotGlobal(); ?>
    <script src="/lib/js/globalBinnacle.js?de=54"></script>

    <script type="text/javascript">
      showListBin();
      function showReserva(){
        $('.ui.viewReserva.modal').modal('show');
      }
      $(".bgt").click(function(){
        $(".bgt").removeClass('active');
        $(this).addClass('active');
      });
      function runBuildBin(){
        $(".ui.newBinnacleModal.modal").modal('show');
      }
      function listadoRes(){
        cleanObjBitacora();
        var filtroperiodo={"filtro":{"inicio":$("#iniBinPer").val(),"fin":$("#finBinPer").val()}};
        bitacora.inicio=$("#iniBinPer").val();
        bitacora.fin=$("#finBinPer").val();
        showList('binnacle',filtroperiodo);
        changeViewBin('construir');
      }

      function printar(){
        //window.location.href="/print/binnacle";
         window.open('/print/binnacle/'+codebinactual, '_blank').focus();
      }

      $('.ui.asigndriverfrm.form').form({ fields:{
          idResAtAsign:{ identifier:'idResAtAsign', rules:[{ type   : 'empty',      prompt : ''}]},
          idDrvToAsing:{ identifier:'idDrvToAsing', rules:[{ type   : 'empty', prompt : ''}]}
        },onSuccess: function(event, fields){
            $.ajax({
              url: "/asingDriverToRes", type: 'POST', data: fields ,
              success: function(data) {
                console.log(data);
                if(data==1){
                  tostadora(1,"Conductor asignado correctamente");
                  $('.ui.asigndrivermod.modal').modal('hide');
                  showList();
                }else{
                  tostadora(4,"Uno o varios registros no se guardaron, verifique su informacion");
                }
              }
            });
      }});

      $('.ui.newBinnaclefrm.form').form({ fields:{
          newBinName:{ identifier:'newBinName', rules:[{ type   : 'empty',      prompt : ''}]},
          newBinStat:{ identifier:'newBinStat', rules:[{ type   : 'empty', prompt : ''}]}
        },onSuccess: function(event, fields){
            bitacora.nombre=fields.newBinName;
            bitacora.stat=fields.newBinStat;
            if(bitacora.reservas.length < 1 ){
              alert("Error: \n Asigne al menos una reserva.");
              return 0;
            }
            $("#newbinsavebtn").addClass("loading");
            $.ajax({
              url: "/setNewBinnacle", type: 'POST', data:bitacora  ,
              success: function(data) {
                //console.log(data);
                if(data==1){
                  tostadora(1,"Bitacora creada correctamente");
                  $('.ui.newBinnacleModal.modal').modal('hide');
                  cleanObjBitacora();
                  $("#newBinName").val("");
                  showListBin();
                  changeViewBin('catalogo');
                  showList();
                }else{
                  tostadora(4,"Uno o varios registros no se guardaron, verifique su informacion");
                }
                $("#newbinsavebtn").removeClass("loading");
              }
            });
      }});
    </script>
  </body>
</html>
