<?php
foreach (glob("/../Modules/*.php") as $filename){
    include $filename;
}
use Modules\DESIGN;
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>SAOI</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?php  echo DESIGN::getBasicLibrary();  ?>
    <link href="/lib/css/calentim.min.css" rel="stylesheet"/>
    <script src="/lib/js/moment.min.js"></script>
    <script src="/lib/js/calentim.min.js"></script>
    <style>
      .ui.paddingless.segment{
        padding: 0 !important;
      }
      .configView{
        padding: 10px 0px 0px 0px !important;;
      }
    </style>
    <script>
      var userTarget=0;
    </script>
  </head>
  <body>
    <div class="pusher">
      <?php // echo DESIGN::renderMenuDesk(4);  ?>
      <div class="configView">
        <div class="ui raised segment">
          <div class="ui grey top attached label">
             <h4> <i class="car alternate icon"></i>CONDUCTORES</h4>
          </div>
          <div class="lildivider"></div>
          <div class="">
            <div class="flotaizq jalarriba">
              <div class="ui mini icon green button" onclick="addDriver()">
                <i class="plus icon"></i>&ensp;Nuevo
              </div>
            </div>
            <div class="flotader jalarriba">
              <div class="ui  icon search" >
                <div class="ui right action mini input">
                  <input type="text" name="findt" id="findt" placeholder="Nombre o Referencia" autocomplete="off" >
                  <a class="ui blue mini button" title="Buscar" onclick="showList('target',$('#findt').val())">
                    &ensp;<i class="ui search icon"></i>
                  </a>
                </div>
              </div>
            </div>
            <div class="">&ensp;</div>
          </div>
          <div class="ui divider"></div>
          <table class="ui selectable celled table" id="example">
            <thead>
              <tr align="center">
                <td class="two wide subtitleBlack">Codigo</td>
                <td class="two wide subtitleBlack">Nombre</td>
                <td class="one wide subtitleBlack">Email</td>
                <td class="one wide subtitleBlack">Telefono</td>
                <td class="two wide subtitleBlack">Estatus</td>
              </tr>
            </thead>
            <tbody id="datamaster" style="font-size: .8rem;"></tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="ui mini viewAddDrvr basic modal">
      <i class="icon close" style="display:none;" id="closmodview"></i>
      <div class="ui segment" id="frmnewoff">
        <div class="ui top attached blue label">
          <div class="flotaizq">
            Nuevo Conductor
          </div>
          <div class="flotader"><i class="icon close" onclick="$('#closmodview').trigger('click')"></i></div>
        </div>
        <div class="ui setNewDriver form">
          <input type="hidden" name="drvOpc" id="drvOpc" value="nuevo">
          <div class="field">
            <label for="">Codigo</label>
            <input type="text" name="drvCode" id="drvCode" value=""placeholder="ej. agente1" autocomplete="off">
          </div>
          <div class="field">
            <label for="">Nombre</label>
            <input type="text" name="drvName" id="drvName" value=""placeholder="ej. Juan Topo" autocomplete="off">
          </div>
          <div class="field">
            <label for="">Email</label>
            <input type="text" name="drvEmail" id="drvEmail" value=""placeholder="ej. agente1@browns.com" autocomplete="off">
          </div>
          <div class="field">
            <label for="">Telefono</label>
            <input type="text" name="drvTel" id="drvTel" value=""placeholder="ej. 624-000-0000" autocomplete="off">
          </div>
          <div class="field" align="center">
            <div class="ui blue submit mini button">
              Guardar&ensp;<i class="save icon"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="ui mini viewEditDrvr basic modal">
      <i class="icon close" style="display:none;" id="closmodview2"></i>
      <div class="ui segment" id="frmnewoff">
        <div class="ui top attached blue label">
          <div class="flotaizq">
            Editar Usuario
          </div>
          <div class="flotader"><i class="icon close" onclick="$('#closmodview2').trigger('click')"></i></div>
        </div>
        <div class="ui setEditDriver form">
          <input type="hidden" name="drvEdtOpc" id="drvEdtOpc" value="editDriver">
          <input type="hidden" name="drvEdtCode" id="drvEdtCode"  autocomplete="off">
          <div class="field">
            <label for="">Usuario:&ensp;
              <span class="subtitleBlack" align="left" id="lbldrvEdtCode"></span>
            </label>
          </div>
          <div class="field">
            <label for="">Nombre</label>
            <input type="text" name="drvEdtName" id="drvEdtName" value=""placeholder="ej. Juan Topo" autocomplete="off">
          </div>
          <div class="field">
            <label for="">Email</label>
            <input type="text" name="drvEdtEmail" id="drvEdtEmail" value=""placeholder="ej. driver@browns.com" autocomplete="off">
          </div>
          <div class="field">
            <label for="">Telefono</label>
            <input type="text" name="drvEdtTel" id="drvEdtTel" value=""placeholder="ej. 624-000-0000" autocomplete="off">
          </div>

          <div class="field">
            <label for="">Estatus</label>
            <select name="drvEdtStat" id="drvEdtStat" class="ui dropdown mini input">
              <option value="1">Activo</option>
              <option value="0">Inactivo</option>
            </select>
          </div>
          <div class="field" align="right">
            <div class="ui red mini button" onclick="delAgent()">
              Eliminar&ensp;<i class="trash icon"></i>
            </div>
            <div class="ui blue submit mini button">
              Guardar&ensp;<i class="save icon"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <?php echo DESIGN::getExtendedLibrary(); ?>
    <script src="/lib/js/globalDrivers.js?de=55"></script>

    <script type="text/javascript">
     showList();
      function addDriver(){
        $('.ui.viewAddDrvr.modal').modal('show');
      }
      function editDriver(cual){
        getInfoDriver(cual);
        userTarget=cual;
        $('.ui.viewEditDrvr.modal').modal('show');
      }
      $(".bgt").click(function(){
        $(".bgt").removeClass('active');
        $(this).addClass('active');
      });

      $('.ui.setNewDriver.form').form({ fields:{
          drvCode:{ identifier:'drvCode', rules:[{ type   : 'empty',      prompt : ''}]},
          drvName:{ identifier:'drvName', rules:[{ type   : 'empty', prompt : ''}]},
          drvEmail:{ identifier:'drvEmail', rules:[{ type   : 'empty', prompt : ''}]}
        },onSuccess: function(event, fields){
        //  cargaloader("etLoader");
            $.ajax({
              url: "/setDriverData", type: 'POST', data: fields ,
              success: function(data) {
                if(data==1){
                  tostadora(1,"Conductor creado correctamente");
                  $('.ui.viewAddDrvr.modal').modal('hide');
                  showList();
                }else{
                  tostadora(4,"Uno o varios registros no se guardaron, verifique su informacion");                }
                  //  cargaloader("etLoader");
              }
            });
      }});

      $('.ui.setEditDriver.form').form({ fields:{
          drvEdtName:{ identifier:'drvEdtName', rules:[{ type   : 'empty',      prompt : ''}]},
          drvEdtEmail:{ identifier:'drvEdtEmail', rules:[{ type   : 'empty', prompt : ''}]}
        },onSuccess: function(event, fields){
            $.ajax({
              url: "/setDriverData", type: 'POST', data: fields ,
              success: function(data) {
                if(data==1){
                  tostadora(1,"Conductor editado correctamente");
                  $('.ui.viewEditDrvr.modal').modal('hide');
                  showList();
                }else{
                  tostadora(4,"Uno o varios registros no se guardaron, verifique su informacion");
                }
              }
            });
      }});

    </script>
  </body>
</html>
