<?php
foreach (glob("/../Modules/*.php") as $filename){
    include $filename;
}
use Modules\DESIGN;
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>SAOI</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?php
      echo DESIGN::getBasicLibrary();
    ?>
    <link href="/lib/css/calentim.min.css" rel="stylesheet"/>
    <script src="/lib/js/moment.min.js"></script>
    <script src="/lib/js/calentim.min.js"></script>
    <style>
      .ui.paddingless.segment{
        padding: 0 !important;
      }
    </style>
  </head>
  <body onload="setInterval('renue()',300000)">
    <div class="pusher fillContainer">
      <?php
       echo DESIGN::renderMenuDesk(1);
      ?>
      <iframe src="/catReservas" name="principal" width="100%" height="96%" frameborder="0" scrolling="auto" style="position:fixed; bottom:0px;" ></iframe>
    </div>

    <script src="/lib/js/globalInfo.js"></script>
    <script type="text/javascript">
      function renue(){
        $.ajax({
          url: "updateSession",
          success: function(result){
            console.log(result);
          }
        });
      }
      $(document).ready(function(){

      });

      $('.acordionChild').click(function (event) {
        	$('.bgt').accordion('close');
          noTxtmenu();
      });

      $('.ui.accordion').accordion();
      $('.ui.embed').embed();
      $(".bgt").click(function(){
        $(".bgt").removeClass('active');
        $(this).addClass('active');
      });
      //noTxtmenu();
    </script>
  </body>
</html>
