<?php
foreach (glob("/../Modules/*.php") as $filename){
    include $filename;
}
use Modules\DESIGN;
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>SAOI</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?php
      echo DESIGN::getBasicLibrary();
    ?>
    <link href="/lib/css/calentim.min.css" rel="stylesheet"/>
    <script src="/lib/js/moment.min.js"></script>
    <script src="/lib/js/calentim.min.js"></script>
    <style>
      .ui.paddingless.segment{
        padding: 0 !important;
      }
    </style>
  </head>
  <body class="moving-gradient">
    <div class="pusher fillContainer">
      <div class="slide"></div>
      <div class="" align="center">
        <div class="ui segment sombrero" style="max-width:380px; margin-top:-150px!important;">
          <form class="ui login form" style="padding:15px" name="signup" action="verifica" method="POST">

            <div class="fields">
              <div class="six wide field" align="right" >
                <img src="https://brownsprivateservices.com/wp-content/uploads/2021/01/cabo-airport-transportation-by-browns-private-transportation-services-logoNEW-mobile.png" style="width:90px">&emsp;
              </div>
              <div class="ten wide field" align="left" >
                <!--<div class="ui hidden divider">  </div>-->
                <span class="subtitleBrown" style="font-size:1.4em; "> Sistema de Administracion y<br>Operacion Interna</span>
              </div>
            </div>


            <div class="fifteen wide field">
              <div class="ui divider"></div>
            </div>
            <div class="fifteen wide field">
              <div class="ui mini left icon input">
                <i class="user brown icon"></i>
                <input type="text" name="user" id="user" value="" placeholder="USUARIO">
              </div>
            </div>
            <div class="fifteen wide field">
              <div class="ui mini left icon input">
                <i class="key brown icon"></i>
                <input type="password" name="contra" id="contra" value="" placeholder="PASSWORD">
              </div>
            </div>
            <div class="fifteen wide field" align="right">
              <?php
                if(isset($errlog)){
                   if($errlog==4){
                     echo '<div class="ui red label">ERROR: USUARIO NO EXISTE</div><br/><br/>';
                   }
                   if($errlog==3){
                     echo '<div class="ui red label">ERROR: PASSWORD INCORRECTO</div><br/><br/>';
                   }
                 }
              ?>
              <div class="ui blue submit mini button">
                Login
              </div>
            </div>
            <div class="fifteen wide field">
              <div class="ui divider"></div>
            </div>
            <div class="field">
              <div class="ui error message"></div>
            </div>
          </form>
        </div>
      </div>
    </div>

    <script src="/lib/js/calendas.js"></script>
    <script type="text/javascript">
      $('.ui.embed').embed();
      function restaurador(){
        $(".ui.resetpass.modal").modal('show');
      }
      $('.ui.login.form').form({ fields:{
         user:{ identifier:'user',
           rules:[{ type   : 'minLength[4]',      prompt : 'Usuario contiene menos de 4 caracteres'}]},
         contra:{ identifier:'contra',
           rules:[{ type   : 'minLength[4]',      prompt : 'Password contiene menos de 4 caracteres'}]}
       }});
    </script>
  </body>
</html>
